"""
"""
import itertools
import re
import numpy
from rvlm.labhelpers.trivia import omit_empty_items


def read_agilent_waveform(stream):
    """
    Reads data from file generated by Agilent oscilloscope. This function reads
    given `stream`, parses it, and reads into a `numpy` array. For example:

    """
    try:
        iterator = iter(stream)
        iterator = itertools.dropwhile(lambda s: s.strip() != "Data,", iterator)
        iterator.next()
        return numpy.loadtxt(iterator, delimiter=", ")
    except StopIteration:
        return None


def read_cst_ascii(stream):
    """
    Reads data from ASCII data file, exported by CST Microwave Studio. Since
    CST can put multiple signals into a single file, this function returns
    a hash of signals, where signal names are keys.
    """
    header_regex = re.compile('\\s\\s+')
    result = {}
    try:
        iterator = iter(stream)
        while True:
            section = itertools.takewhile(lambda s: s.strip() != "",  iterator)
            header = section.next()
            (xhdr, yhdr) = omit_empty_items(header_regex.split(header))

            separator_line = section.next()
            separator_line = separator_line.strip()
            if not all(map(lambda ch: ch == '-', separator_line)):
                break

            result[yhdr] = numpy.loadtxt(section)

    except StopIteration:
        pass

    return result
